/** Menu layout. Items are command ids; '-' is a separator. */
export interface MenuDef {
  label: string;
  items: string[];
}

export const MENUS: MenuDef[] = [
  {
    label: 'File',
    items: ['file.new', 'file.open', 'file.openProject', 'file.place', '-', 'file.save', 'file.saveAs', 'file.export', '-', 'file.close'],
  },
  {
    label: 'Edit',
    items: [
      'edit.undo',
      'edit.redo',
      '-',
      'edit.cut',
      'edit.copy',
      'edit.copyMerged',
      'edit.paste',
      'edit.clear',
      '-',
      'edit.fillForeground',
      'edit.fillBackground',
      '-',
      'edit.freeTransform',
      'edit.flipH',
      'edit.flipV',
      'edit.rotateCW',
      'edit.rotateCCW',
      'edit.rotate180',
    ],
  },
  {
    label: 'Image',
    items: [
      'image.size',
      'image.canvasSize',
      'image.cropToSelection',
      '-',
      'image.rotateCW',
      'image.rotateCCW',
      'image.rotate180',
      'image.flipH',
      'image.flipV',
    ],
  },
  {
    label: 'Layer',
    items: [
      'layer.new',
      'layer.newGroup',
      'layer.duplicate',
      'layer.delete',
      '-',
      'layer.group',
      'layer.ungroup',
      '-',
      'layer.addMask',
      'layer.addMaskHide',
      'layer.toggleMask',
      'layer.invertMask',
      'layer.applyMask',
      'layer.deleteMask',
      'layer.editContent',
      'layer.editMask',
      '-',
      'layer.bringToFront',
      'layer.bringForward',
      'layer.sendBackward',
      'layer.sendToBack',
      '-',
      'layer.clip',
      'layer.rasterize',
      '-',
      'layer.mergeDown',
      'layer.mergeVisible',
      'layer.flatten',
    ],
  },
  {
    label: 'Select',
    items: ['select.all', 'select.deselect', 'select.reselect', 'select.inverse', '-', 'select.feather', 'select.loadTransparency'],
  },
  {
    label: 'Adjust',
    items: [
      'adjust.brightnessContrast',
      'adjust.levels',
      'adjust.curves',
      'adjust.exposure',
      'adjust.shadowsHighlights',
      '-',
      'adjust.vibrance',
      'adjust.hueSaturation',
      'adjust.whiteBalance',
      'adjust.blackWhite',
    ],
  },
  { label: 'Filter', items: ['adjust.gaussianBlur', 'adjust.sharpen'] },
  {
    label: 'View',
    items: [
      'view.zoomIn',
      'view.zoomOut',
      'view.fit',
      'view.actualPixels',
      'view.printSize',
      '-',
      'view.rulers',
      'view.pixelGrid',
      '-',
      'view.maskGrayscale',
      'view.maskOverlay',
    ],
  },
  { label: 'Help', items: ['help.shortcuts', 'help.about'] },
];
